[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "structured_optics"
version = "0.4.1"
description = "Package for Structured Light simulation"
readme = "README.md"
license = "BSD-3-Clause"
requires-python = ">=3.9"
authors = [
    { name = "Altilano C. Barbosa" }
]

dependencies = [
    "numpy",
    "scipy",
    "screeninfo"
]
